### PR TITLE
Fix CallId codec

### LINKED ISSUE #16: CallId codec doesn't handle strings
Whereas I think it should, right?

```scala
//> using lib "tech.neander::jsonrpclib-fs2:0.0.3"

import com.github.plokhotnyuk.jsoniter_scala.core.*

@main def hello = 
  readFromStringReentrant[jsonrpclib.CallId]("25")
  readFromStringReentrant[jsonrpclib.CallId](""" "25" """.trim)
```

```
$ scli test.scala
Exception in thread "main" com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected end of input, offset: 0x00000002, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00000000 | 22 32 35 22                                     | "25"             |
+----------+-------------------------------------------------+------------------+
```

### PR DESCRIPTION
**Pull request by keynmol**
Closes #16 

I also removed the `Try` approach because, perhaps naively, on something like id decoding we can save allocations (but not on exception throwing)

### CODE REVIEW

File: core/src/jsonrpclib/CallId.scala [hunk 1]
```diff
@@ -10,12 +9,20 @@ object CallId {
...
+        case _: JsonReaderException =>
+          in.rollbackToken()
+          try {
+            StringId(in.readString(null))
+          } catch {
+            case _: JsonReaderException =>
+              in.readNullOrError(default, "expected null")
+          }
+      }
+    }
```
Comment (keynmol) [inline core/src/jsonrpclib/CallId.scala:25]: @plokhotnyuk is this the way to write codecs like this? I'm not super familiar with jsoniter, so might need some guidance.

File: core/src/jsonrpclib/CallId.scala [hunk 2]
```diff
@@ -10,12 +9,20 @@ object CallId {
...
-        .map(NumberId(_): CallId)
-        .orElse(Try(in.readString(null)).map(StringId(_): CallId))
-        .orElse(scala.util.Success(default))
-        .get
+    def decodeValue(in: JsonReader, default: CallId): CallId = {
+      try {
+        NumberId(in.readLong())
+      } catch {
+        case _: JsonReaderException =>
+          in.rollbackToken()
```
Comment (keynmol) [inline core/src/jsonrpclib/CallId.scala:17]: This is the key thing - 1 token is already consumed, it's the wrong kind (not number), so we need to roll back, so that a string can be read

Comment (Baccata) [reply core/src/jsonrpclib/CallId.scala:17]: oh right, yeah, my bad. I think the implementation is fine, though you could optimise by using `isNextToken` to check whether the first char is a `'"'` or `'n'`and dispatch to `readString`, `readNull` or `readLong` depending on the result. Not sure you need to rollback after peeking at the next token.

Comment (keynmol) [reply core/src/jsonrpclib/CallId.scala]: Good idea - I was originally thinking to reject it because both nextToken and isNextToken actually move the pointer (there's no peeking it seems), but implementation in https://github.com/neandertech/jsonrpclib/pull/19/commits/c9f19e64464c7bb272d36fd194d0efc33f1dd40e does the same thing and doesn't rely on costly exceptions.

**Review by Baccata — APPROVED** [review]
